// Pixel-art sprite library. Each sprite is an array of strings; characters map to PAL colors.
export const PAL = {
  K: '#0a0a0a',
  R: '#e11d48',
  r: '#9f1239',
  B: '#1d4ed8',
  b: '#1e3a8a',
  N: '#0f172a',
  n: '#1e293b',
  W: '#f8fafc',
  G: '#94a3b8',
  g: '#475569',
  O: '#f97316',
  Y: '#facc15',
  T: '#22c55e',
  E: '#38bdf8',
};

export const SPRITES = {
  spider: [
    '......KK......',
    '...K..KK..K...',
    '....K.KK.K....',
    '..K.KKKKKK.K..',
    '...KKKKKKKK...',
    'K.KKWKKKKWKK.K',
    '.KKKKKKKKKKK..',
    '..KKKKKKKK.K..',
    '.K.KKKKKK.K...',
    'K..K.KK.K..K..',
  ],
  cursor: [
    'K......K',
    '.K....K.',
    '..K..K..',
    'KKKKKKKK',
    'KKWKKWKK',
    'KKKKKKKK',
    '..K..K..',
    '.K....K.',
    'K......K',
  ],
  terminal: [
    'KKKKKKKKKKKKKKKK',
    'KNNNNNNNNNNNNNNK',
    'KN............NK',
    'KN.TT.........NK',
    'KN..TT........NK',
    'KN.TT.........NK',
    'KN......TTTT..NK',
    'KN............NK',
    'KNNNNNNNNNNNNNNK',
    'KKKKKKKKKKKKKKKK',
  ],
  folder: [
    '................',
    '..RRRRRR........',
    '.RRRRRRRRRRRRR..',
    '.RRRRRRRRRRRRRRR',
    '.RrrRRRRRRRRRRRR',
    '.RRRRRRRRRRRRRRR',
    '.RRRRRRRRRRRRRRR',
    '.RRRRRRRRRRRRRRR',
    '.RRRRRRRRRRRRRRR',
    '..RRRRRRRRRRRRR.',
  ],
  aiEnhance: [
    'KKKKKKKKKKKKKKKK',
    'KEEEEEEEEEEEEEEK',
    'KEEYEEEEEEEEEEEK',
    'KEYEYEEEEEWWEEEK',
    'KEEYEEEEEEWWEEEK',
    'KEEEbbEEEEEEEEEK',
    'KEEbbbbbbEEWEEEK',
    'KEbbbbbbbbEEEEEK',
    'KbbbbbbbbbbEEEEK',
    'KKKKKKKKKKKKKKKK',
    '................',
    '..W.........W...',
    '....W...W...W...',
    '..W.........W...',
  ],
  instaDown: [
    '...KKKKKKKKK....',
    '...KWWWWWWWK....',
    '...KWKWWKWWK....',
    '...KWWWWWWWK....',
    '...KWKWWKWWK....',
    '...KWWWWWWWK....',
    '...KWKWWKWWK....',
    '...KWWWWWWWK....',
    '...KWWWWWWWK....',
    '...KKKKKKKKK....',
    '......TTT.......',
    '......TTT.......',
    '....TTTTTTT.....',
    '.....TTTTT......',
    '......TTT.......',
    '.......T........',
  ],
  verify: [
    'KK..........KK',
    'K............K',
    'K..WWWWWW....K',
    'K.WWKWWKWW...K',
    'K.WWWWWWWW...K',
    'K..WWKKWW....K',
    'K...WWWW.....K',
    'K............K',
    'KK..........KK',
    '......CC......',
    '....CCCCCC....',
    '..CCCCCCCCCC..',
    '....CCCCCC....',
    '......CC......',
  ],
  hospital: [
    'KKKKKKKKKKKKKKKK',
    'KNNNNNNNNNNNNNNK',
    'KN...RR.......NK',
    'KN..RRRR......NK',
    'KN..RRRR......NK',
    'KN.RRRRRR.....NK',
    'KN..RRRR......NK',
    'KN..RRRR..T...NK',
    'KN...RR...T.T.NK',
    'KN.....T.T.T..NK',
    'KN.TTTTTTTTT..NK',
    'KNNNNNNNNNNNNNNK',
    'KKKKKKKKKKKKKKKK',
    '.......KK.......',
    '.....KKKKKK.....',
  ],
  ecom: [
    '......KKKK......',
    '....KKOOOOKK....',
    '...KOOOOOOOOK...',
    'KKKKKKKKKKKKKK..',
    'KOOOOOKKOOOOOK..',
    'KOOOOOKKOOOOOK..',
    'KOOOOOKKOOOOOK..',
    'KOOOOOKKOOOOOK..',
    'KKKKKKKKKKKKKK..',
    '............TT..',
    '..T........TTT..',
    '..TT..T..TTTTT..',
    '..TTTTTTTTTTTT..',
    '..TTTTTTTTTTTT..',
  ],
  blog: [
    'KKKKKKKKKKKKKKKK',
    'KRKYKGKKKKKKKKKK',
    'KKKKKKKKKKKKKKKK',
    'KWWWWWWWWWWWWWWK',
    'KWKKKKKWWWWWWWWK',
    'KWKWWWWWWWWWWWWK',
    'KWKWWKWKWKWKWWWK',
    'KWKWWWWWWWWWWWWK',
    'KWKWWKWKWKWWWWWK',
    'KWKWWWWWWWWWWWWK',
    'KWKKKKKKKKKKKKWK',
    'KWWWWWWWWWWWWWWK',
    'KKKKKKKKKKKKKKKK',
  ],
  suit: [
    '....KKKKKKKK....',
    '..KKRRRRRRRRKK..',
    '.KRRRRRRRRRRRRK.',
    '.RRWWKRRRRKWWRR.',
    '.RRRRRRRRRRRRRR.',
    '.KRRRKKKKKKRRRK.',
    '..RRRKRRRRKRRR..',
    '..RRRRRRRRRRRR..',
    '..BBRRRRRRRRBB..',
    '..BBBBRRRRBBBB..',
    '..BBBB.KK.BBBB..',
    '..KKKK....KKKK..',
  ],
  github: [
    '....KKKKKKKK....',
    '...KKKKKKKKKK...',
    '..KKKKKKKKKKKK..',
    '..KKWWKKKKWWKK..',
    '..KKWKKKKKKWKK..',
    '..KKKKKKKKKKKK..',
    '..KKKKKKKKKKKK..',
    '...KKK.KK.KKK...',
    '...KK.KKKK.KK...',
    '....KKKKKKKK....',
  ],
  linkedin: [
    'KKKKKKKKKKKKKKK',
    'KBBBBBBBBBBBBBK',
    'KBWWBKBBBBBBBBK',
    'KBWWBKBBBBBBBBK',
    'KBBBBKBBBBBBBBK',
    'KBWWBKBBKBBBBBK',
    'KBWWBKBBKBBBBBK',
    'KBWWBKBBKBBBBBK',
    'KBWWBKBBKBBBBBK',
    'KBBBBBBBBBBBBBK',
    'KKKKKKKKKKKKKKK',
  ],
  instagram: [
    'KKKKKKKKKKKKKK',
    'KOOOOOOOOOOOOK',
    'KOOWWKOOOOKOOK',
    'KOOWWKOOOKKKOK',
    'KOOOOOOKKWKKOK',
    'KOOOOOKWWWWKOK',
    'KOOOOOKWKKWKOK',
    'KOOOOOKWWWWKOK',
    'KOOOOOOKKWKKOK',
    'KOOOOOOOKKKOOK',
    'KOOOOOOOOOOOOK',
    'KKKKKKKKKKKKKK',
  ],
  resume: [
    '..KKKKKKKKKK....',
    '..KWWWWWWWWK....',
    '..KWKKKKKKWKK...',
    '..KWWWWWWWWWK...',
    '..KWKKKKKKWWK...',
    '..KWWWWWWWWWK...',
    '..KWKKKWWWWWK...',
    '..KWWWWWWWWWK...',
    '..KWKKKKKKWWK...',
    '..KWWWWWWWWWK...',
    '..KKKKKKKKKKK...',
  ],
  contact: [
    'KKKKKKKKKKKKKKKK',
    'KRRRRRRRRRRRRRRK',
    'KRKRRRRRRRRRRKRK',
    'KRRKRRRRRRRRKRRK',
    'KRRRKRRRRRRKRRRK',
    'KRRRRKRRRRKRRRRK',
    'KRRRRRKRRKRRRRRK',
    'KRRRRRRKKRRRRRRK',
    'KRRRRRRRRRRRRRRK',
    'KKKKKKKKKKKKKKKK',
  ],
  trash: [
    '.....KKKKKK.....',
    '....KKKKKKKK....',
    '..KKKKKKKKKKKK..',
    '...KGGGGGGGGK...',
    '...KGgGgGgGgGK..',
    '...KGgGgGgGgGK..',
    '...KGgGgGgGgGK..',
    '...KGgGgGgGgGK..',
    '...KGgGgGgGgGK..',
    '....KGGGGGGK....',
  ],
  skills: [
    '.......RR.......',
    '...R...RR...R...',
    '....R..RR..R....',
    '.....RRRRRR.....',
    '.RRRRRRWWRRRRRR.',
    '.RRRRRWWWWRRRRR.',
    '.....RRRRRR.....',
    '....R..RR..R....',
    '...R...RR...R...',
    '.......RR.......',
  ],
  moon: [
    '.....WWWW......',
    '...WWWWWWWW....',
    '..WWGGWWWWWW...',
    '..WGGGWWWWWWW..',
    '.WWGGWWWWWWWWW.',
    '.WWWWWWWWWGGWW.',
    '.WWWWWWWWGGGW..',
    '..WWWWWWWWWW...',
    '...WWWWWWWW....',
    '.....WWWW......',
  ],
  finder: [
    'KKKKKKKKKKKKKKKK',
    'KEEEEEEEEEEEEEEK',
    'KEEEEEEEEEEEEEEK',
    'KEEKKKEEEEKKKEEK',
    'KEEKKKEEEEKKKEEK',
    'KEEEEEEEEEEEEEEK',
    'KEEEEEKKEEEEEEEK',
    'KEEEEEKKEEEEEEEK',
    'KEEKKEEEEEEKKEEK',
    'KEEEKKKKKKKKEEEK',
    'KEEEEEEEEEEEEEEK',
    'KKKKKKKKKKKKKKKK',
  ],
  character: [
    '........RRRRRRRR........',
    '......RRRRRRRRRRRR......',
    '.....RRRRRRRRRRRRRR.....',
    '....RRWWRRRRRRRRWWRR....',
    '....RWWWWRRRRRRWWWWR....',
    '....RWWKKRRRRRRKKWWR....',
    '....RRWWRRRRRRRRWWRR....',
    '.....RRRRRRRRRRRRRR.....',
    '......RRRRRRRRRRRR......',
    '.......RRRRRRRRRR.......',
    '........RRRKKRRR........',
    '.....RRRRRRRRRRRRRR.....',
    '....RRRRRRRRRRRRRRRR....',
    '...BBBRRRRRRRRRRRRBBB...',
    '..BBBBRRRRRRRRRRRBBBB...',
    '..BBB.RRRRRRRRRRR.BBB...',
    '..BBB.RRRRRRRRRRR.BBB...',
    '..BBB.RRRRRRRRRRR.BBB...',
    '..KKK.RRRRRRRRRRR.KKK...',
    '......RRRRRRRRRRRR......',
    '......RRRRR..RRRRR......',
    '......BBBB....BBBB......',
    '......BBBB....BBBB......',
    '......BBBB....BBBB......',
    '......KKKK....KKKK......',
  ],
};
